apiVersion: v1
kind: Service
metadata:
  name: cognitionlabs-web
spec:
  selector:
    app: cognitionlabs-web
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
